/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsumg
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuCadastros = new javax.swing.JMenu();
        menuCadastrosClientes = new javax.swing.JMenuItem();
        menuCadastrosMotoristas = new javax.swing.JMenuItem();
        menuCadastrosEntregas = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasListaClientes = new javax.swing.JMenuItem();
        menuConsultasListaMotoristas = new javax.swing.JMenuItem();
        menuConsultasListaEntregas = new javax.swing.JMenuItem();
        menuRoteirizacao = new javax.swing.JMenu();
        menuRoteirizacaoGerar = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelatoriosConsulta = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaManual = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysRouter - Versão 1.0");
        setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");
        menuArquivo.setName("menuArquivo"); // NOI18N

        menuArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        barraMenu.add(menuArquivo);

        menuEditar.setText("Editar");
        menuEditar.setName("menuEditar"); // NOI18N
        barraMenu.add(menuEditar);

        menuCadastros.setText("Cadastros");
        menuCadastros.setName("menuCadastros"); // NOI18N

        menuCadastrosClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrosClientes.setText("Cadastro de Clientes");
        menuCadastrosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosClientes);

        menuCadastrosMotoristas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrosMotoristas.setText("Cadastro de Motoristas");
        menuCadastrosMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosMotoristasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosMotoristas);

        menuCadastrosEntregas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrosEntregas.setText("Cadastro de Entregas");
        menuCadastrosEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosEntregasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosEntregas);

        barraMenu.add(menuCadastros);

        menuConsultas.setText("Consultas");

        menuConsultasListaClientes.setText("Lista de Clientes");
        menuConsultasListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasListaClientesActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasListaClientes);

        menuConsultasListaMotoristas.setText("Lista de Motoristas");
        menuConsultas.add(menuConsultasListaMotoristas);

        menuConsultasListaEntregas.setText("Lista de Entregas");
        menuConsultas.add(menuConsultasListaEntregas);

        barraMenu.add(menuConsultas);

        menuRoteirizacao.setText("Roteirização");
        menuRoteirizacao.setName("menuRoteirizacao"); // NOI18N

        menuRoteirizacaoGerar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuRoteirizacaoGerar.setText("Gerar Roteirização");
        menuRoteirizacao.add(menuRoteirizacaoGerar);

        barraMenu.add(menuRoteirizacao);

        menuRelatorio.setText("Relatórios");
        menuRelatorio.setName("menuRelatorios"); // NOI18N

        menuRelatoriosConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatoriosConsulta.setText("Consultar Entregas");
        menuRelatoriosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosConsultaActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatoriosConsulta);

        barraMenu.add(menuRelatorio);

        menuAjuda.setText("Ajuda");
        menuAjuda.setName("menuAjuda"); // NOI18N

        menuAjudaManual.setText("Manual de Utilização");
        menuAjudaManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaManualActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjudaManual);
        menuAjuda.add(jSeparator2);

        menuAjudaSobre.setText("Sobre");
        menuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjudaSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosClientesActionPerformed
        JInternalFrame formCliente = new FormCliente();
        desktop.add(formCliente);
        formCliente.setVisible(true);
    }//GEN-LAST:event_menuCadastrosClientesActionPerformed

    private void menuCadastrosMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosMotoristasActionPerformed
        JInternalFrame formMotorista = new FormMotorista();
        desktop.add(formMotorista);
        formMotorista.setVisible(true);
    }//GEN-LAST:event_menuCadastrosMotoristasActionPerformed

    private void menuAjudaManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaManualActionPerformed

    }//GEN-LAST:event_menuAjudaManualActionPerformed

    private void menuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAjudaSobreActionPerformed

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        int encerrar = JOptionPane.showConfirmDialog(null, "Deseja mesmo encerrar o SysRouter?");
        if (encerrar == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    private void menuCadastrosEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosEntregasActionPerformed
        JInternalFrame formEntregas = new FormEntregas();
        desktop.add(formEntregas);
        formEntregas.setVisible(true);
    }//GEN-LAST:event_menuCadastrosEntregasActionPerformed

    private void menuRelatoriosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosConsultaActionPerformed
        JInternalFrame formConsulta = new FormConsulta();
        desktop.add(formConsulta);
        formConsulta.setVisible(true);
    }//GEN-LAST:event_menuRelatoriosConsultaActionPerformed

    private void menuConsultasListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasListaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultasListaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaManual;
    private javax.swing.JMenuItem menuAjudaSobre;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCadastrosClientes;
    private javax.swing.JMenuItem menuCadastrosEntregas;
    private javax.swing.JMenuItem menuCadastrosMotoristas;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasListaClientes;
    private javax.swing.JMenuItem menuConsultasListaEntregas;
    private javax.swing.JMenuItem menuConsultasListaMotoristas;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuRelatoriosConsulta;
    private javax.swing.JMenu menuRoteirizacao;
    private javax.swing.JMenuItem menuRoteirizacaoGerar;
    // End of variables declaration//GEN-END:variables
}
